language: java
jdk:
- oraclejdk8

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$API_KEY@github.com/cworks/json-io --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $API_KEY
  file:
    - "build/libs/json-io-1.5.jar"
  on:
    repo: cworks/json-io
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
